apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: ipam.miloapis.com-ipallocation
spec:
  serviceRef:
    name: "ipam.miloapis.com"
  kind: IPAllocation
  plural: ipallocations
  singular: ipallocation
  permissions:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
    - updateStatus
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
