apiVersion: iam.miloapis.com/v1alpha1
kind: ProtectedResource
metadata:
  name: ipam.miloapis.com-ipclaim
spec:
  serviceRef:
    name: "ipam.miloapis.com"
  kind: IPClaim
  plural: ipclaims
  singular: ipclaim
  permissions:
    - list
    - get
    - watch
    - create
    - update
    - patch
    - delete
    - updateStatus
  parentResources:
    - apiGroup: resourcemanager.miloapis.com
      kind: Project
