// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	fmt "fmt"

	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=ipam.miloapis.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("asnclaims"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().ASNClaims().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("asnpools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().ASNPools().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("asnpoolclasses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().ASNPoolClasses().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipaddresses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().IPAddresses().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipaddressclaims"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().IPAddressClaims().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipprefixes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().IPPrefixes().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipprefixclaims"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().IPPrefixClaims().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("ipprefixclasses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ipam().V1alpha1().IPPrefixClasses().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
