// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPools implements IPPoolInterface
type fakeIPPools struct {
	*gentype.FakeClientWithList[*v1alpha1.IPPool, *v1alpha1.IPPoolList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPPools(fake *FakeIpamV1alpha1) ipamv1alpha1.IPPoolInterface {
	return &fakeIPPools{
		gentype.NewFakeClientWithList[*v1alpha1.IPPool, *v1alpha1.IPPoolList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("ippools"),
			v1alpha1.SchemeGroupVersion.WithKind("IPPool"),
			func() *v1alpha1.IPPool { return &v1alpha1.IPPool{} },
			func() *v1alpha1.IPPoolList { return &v1alpha1.IPPoolList{} },
			func(dst, src *v1alpha1.IPPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPPoolList) []*v1alpha1.IPPool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPPoolList, items []*v1alpha1.IPPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
