// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPClaims implements IPClaimInterface
type fakeIPClaims struct {
	*gentype.FakeClientWithList[*v1alpha1.IPClaim, *v1alpha1.IPClaimList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPClaims(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.IPClaimInterface {
	return &fakeIPClaims{
		gentype.NewFakeClientWithList[*v1alpha1.IPClaim, *v1alpha1.IPClaimList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ipclaims"),
			v1alpha1.SchemeGroupVersion.WithKind("IPClaim"),
			func() *v1alpha1.IPClaim { return &v1alpha1.IPClaim{} },
			func() *v1alpha1.IPClaimList { return &v1alpha1.IPClaimList{} },
			func(dst, src *v1alpha1.IPClaimList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPClaimList) []*v1alpha1.IPClaim { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPClaimList, items []*v1alpha1.IPClaim) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
