// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIpamV1alpha1 struct {
	*testing.Fake
}

func (c *FakeIpamV1alpha1) IPAllocations(namespace string) v1alpha1.IPAllocationInterface {
	return newFakeIPAllocations(c, namespace)
}

func (c *FakeIpamV1alpha1) IPClaims(namespace string) v1alpha1.IPClaimInterface {
	return newFakeIPClaims(c, namespace)
}

func (c *FakeIpamV1alpha1) IPPools() v1alpha1.IPPoolInterface {
	return newFakeIPPools(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIpamV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
