// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAddressClaims implements IPAddressClaimInterface
type fakeIPAddressClaims struct {
	*gentype.FakeClientWithList[*v1alpha1.IPAddressClaim, *v1alpha1.IPAddressClaimList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPAddressClaims(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.IPAddressClaimInterface {
	return &fakeIPAddressClaims{
		gentype.NewFakeClientWithList[*v1alpha1.IPAddressClaim, *v1alpha1.IPAddressClaimList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ipaddressclaims"),
			v1alpha1.SchemeGroupVersion.WithKind("IPAddressClaim"),
			func() *v1alpha1.IPAddressClaim { return &v1alpha1.IPAddressClaim{} },
			func() *v1alpha1.IPAddressClaimList { return &v1alpha1.IPAddressClaimList{} },
			func(dst, src *v1alpha1.IPAddressClaimList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPAddressClaimList) []*v1alpha1.IPAddressClaim {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IPAddressClaimList, items []*v1alpha1.IPAddressClaim) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
