// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPrefixes implements IPPrefixInterface
type fakeIPPrefixes struct {
	*gentype.FakeClientWithList[*v1alpha1.IPPrefix, *v1alpha1.IPPrefixList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPPrefixes(fake *FakeIpamV1alpha1) ipamv1alpha1.IPPrefixInterface {
	return &fakeIPPrefixes{
		gentype.NewFakeClientWithList(
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("ipprefixes"),
			v1alpha1.SchemeGroupVersion.WithKind("IPPrefix"),
			func() *v1alpha1.IPPrefix { return &v1alpha1.IPPrefix{} },
			func() *v1alpha1.IPPrefixList { return &v1alpha1.IPPrefixList{} },
			func(dst, src *v1alpha1.IPPrefixList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPPrefixList) []*v1alpha1.IPPrefix { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPPrefixList, items []*v1alpha1.IPPrefix) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
