// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeASNClaims implements ASNClaimInterface
type fakeASNClaims struct {
	*gentype.FakeClientWithList[*v1alpha1.ASNClaim, *v1alpha1.ASNClaimList]
	Fake *FakeIpamV1alpha1
}

func newFakeASNClaims(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.ASNClaimInterface {
	return &fakeASNClaims{
		gentype.NewFakeClientWithList[*v1alpha1.ASNClaim, *v1alpha1.ASNClaimList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("asnclaims"),
			v1alpha1.SchemeGroupVersion.WithKind("ASNClaim"),
			func() *v1alpha1.ASNClaim { return &v1alpha1.ASNClaim{} },
			func() *v1alpha1.ASNClaimList { return &v1alpha1.ASNClaimList{} },
			func(dst, src *v1alpha1.ASNClaimList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ASNClaimList) []*v1alpha1.ASNClaim { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ASNClaimList, items []*v1alpha1.ASNClaim) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
