// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeIpamV1alpha1 struct {
	*testing.Fake
}

func (c *FakeIpamV1alpha1) IPAddresses(namespace string) v1alpha1.IPAddressInterface {
	return newFakeIPAddresses(c, namespace)
}

func (c *FakeIpamV1alpha1) IPAddressClaims(namespace string) v1alpha1.IPAddressClaimInterface {
	return newFakeIPAddressClaims(c, namespace)
}

func (c *FakeIpamV1alpha1) IPPrefixes() v1alpha1.IPPrefixInterface {
	return newFakeIPPrefixes(c)
}

func (c *FakeIpamV1alpha1) IPPrefixClaims(namespace string) v1alpha1.IPPrefixClaimInterface {
	return newFakeIPPrefixClaims(c, namespace)
}

func (c *FakeIpamV1alpha1) IPPrefixClasses() v1alpha1.IPPrefixClassInterface {
	return newFakeIPPrefixClasses(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeIpamV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
