// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeASNPools implements ASNPoolInterface
type fakeASNPools struct {
	*gentype.FakeClientWithList[*v1alpha1.ASNPool, *v1alpha1.ASNPoolList]
	Fake *FakeIpamV1alpha1
}

func newFakeASNPools(fake *FakeIpamV1alpha1) ipamv1alpha1.ASNPoolInterface {
	return &fakeASNPools{
		gentype.NewFakeClientWithList[*v1alpha1.ASNPool, *v1alpha1.ASNPoolList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("asnpools"),
			v1alpha1.SchemeGroupVersion.WithKind("ASNPool"),
			func() *v1alpha1.ASNPool { return &v1alpha1.ASNPool{} },
			func() *v1alpha1.ASNPoolList { return &v1alpha1.ASNPoolList{} },
			func(dst, src *v1alpha1.ASNPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ASNPoolList) []*v1alpha1.ASNPool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.ASNPoolList, items []*v1alpha1.ASNPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
