// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAllocations implements IPAllocationInterface
type fakeIPAllocations struct {
	*gentype.FakeClientWithList[*v1alpha1.IPAllocation, *v1alpha1.IPAllocationList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPAllocations(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.IPAllocationInterface {
	return &fakeIPAllocations{
		gentype.NewFakeClientWithList[*v1alpha1.IPAllocation, *v1alpha1.IPAllocationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ipallocations"),
			v1alpha1.SchemeGroupVersion.WithKind("IPAllocation"),
			func() *v1alpha1.IPAllocation { return &v1alpha1.IPAllocation{} },
			func() *v1alpha1.IPAllocationList { return &v1alpha1.IPAllocationList{} },
			func(dst, src *v1alpha1.IPAllocationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPAllocationList) []*v1alpha1.IPAllocation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IPAllocationList, items []*v1alpha1.IPAllocation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
