// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPrefixClaims implements IPPrefixClaimInterface
type fakeIPPrefixClaims struct {
	*gentype.FakeClientWithList[*v1alpha1.IPPrefixClaim, *v1alpha1.IPPrefixClaimList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPPrefixClaims(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.IPPrefixClaimInterface {
	return &fakeIPPrefixClaims{
		gentype.NewFakeClientWithList[*v1alpha1.IPPrefixClaim, *v1alpha1.IPPrefixClaimList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ipprefixclaims"),
			v1alpha1.SchemeGroupVersion.WithKind("IPPrefixClaim"),
			func() *v1alpha1.IPPrefixClaim { return &v1alpha1.IPPrefixClaim{} },
			func() *v1alpha1.IPPrefixClaimList { return &v1alpha1.IPPrefixClaimList{} },
			func(dst, src *v1alpha1.IPPrefixClaimList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPPrefixClaimList) []*v1alpha1.IPPrefixClaim {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IPPrefixClaimList, items []*v1alpha1.IPPrefixClaim) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
