// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPAddresses implements IPAddressInterface
type fakeIPAddresses struct {
	*gentype.FakeClientWithList[*v1alpha1.IPAddress, *v1alpha1.IPAddressList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPAddresses(fake *FakeIpamV1alpha1, namespace string) ipamv1alpha1.IPAddressInterface {
	return &fakeIPAddresses{
		gentype.NewFakeClientWithList[*v1alpha1.IPAddress, *v1alpha1.IPAddressList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("ipaddresses"),
			v1alpha1.SchemeGroupVersion.WithKind("IPAddress"),
			func() *v1alpha1.IPAddress { return &v1alpha1.IPAddress{} },
			func() *v1alpha1.IPAddressList { return &v1alpha1.IPAddressList{} },
			func(dst, src *v1alpha1.IPAddressList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPAddressList) []*v1alpha1.IPAddress { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPAddressList, items []*v1alpha1.IPAddress) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
