// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPClasses implements IPClassInterface
type fakeIPClasses struct {
	*gentype.FakeClientWithList[*v1alpha1.IPClass, *v1alpha1.IPClassList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPClasses(fake *FakeIpamV1alpha1) ipamv1alpha1.IPClassInterface {
	return &fakeIPClasses{
		gentype.NewFakeClientWithList[*v1alpha1.IPClass, *v1alpha1.IPClassList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("ipclasses"),
			v1alpha1.SchemeGroupVersion.WithKind("IPClass"),
			func() *v1alpha1.IPClass { return &v1alpha1.IPClass{} },
			func() *v1alpha1.IPClassList { return &v1alpha1.IPClassList{} },
			func(dst, src *v1alpha1.IPClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPClassList) []*v1alpha1.IPClass { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.IPClassList, items []*v1alpha1.IPClass) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
