// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPrefixClasses implements IPPrefixClassInterface
type fakeIPPrefixClasses struct {
	*gentype.FakeClientWithList[*v1alpha1.IPPrefixClass, *v1alpha1.IPPrefixClassList]
	Fake *FakeIpamV1alpha1
}

func newFakeIPPrefixClasses(fake *FakeIpamV1alpha1) ipamv1alpha1.IPPrefixClassInterface {
	return &fakeIPPrefixClasses{
		gentype.NewFakeClientWithList[*v1alpha1.IPPrefixClass, *v1alpha1.IPPrefixClassList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("ipprefixclasses"),
			v1alpha1.SchemeGroupVersion.WithKind("IPPrefixClass"),
			func() *v1alpha1.IPPrefixClass { return &v1alpha1.IPPrefixClass{} },
			func() *v1alpha1.IPPrefixClassList { return &v1alpha1.IPPrefixClassList{} },
			func(dst, src *v1alpha1.IPPrefixClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IPPrefixClassList) []*v1alpha1.IPPrefixClass {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IPPrefixClassList, items []*v1alpha1.IPPrefixClass) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
