// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/clientset/versioned/typed/ipam/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeASNPoolClasses implements ASNPoolClassInterface
type fakeASNPoolClasses struct {
	*gentype.FakeClientWithList[*v1alpha1.ASNPoolClass, *v1alpha1.ASNPoolClassList]
	Fake *FakeIpamV1alpha1
}

func newFakeASNPoolClasses(fake *FakeIpamV1alpha1) ipamv1alpha1.ASNPoolClassInterface {
	return &fakeASNPoolClasses{
		gentype.NewFakeClientWithList[*v1alpha1.ASNPoolClass, *v1alpha1.ASNPoolClassList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("asnpoolclasses"),
			v1alpha1.SchemeGroupVersion.WithKind("ASNPoolClass"),
			func() *v1alpha1.ASNPoolClass { return &v1alpha1.ASNPoolClass{} },
			func() *v1alpha1.ASNPoolClassList { return &v1alpha1.ASNPoolClassList{} },
			func(dst, src *v1alpha1.ASNPoolClassList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ASNPoolClassList) []*v1alpha1.ASNPoolClass {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ASNPoolClassList, items []*v1alpha1.ASNPoolClass) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
