//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AllocationSpec) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.AllocationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAllocation) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPAllocation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAllocationList) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPAllocationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAllocationSpec) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPAllocationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPAllocationStatus) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPAllocationStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPClaim) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPClaim"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPClaimList) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPClaimList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPClaimSpec) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPClaimSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPClaimStatus) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPClaimStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPool) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolList) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolSpec) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in IPPoolStatus) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.IPPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalRef) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.LocalRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NamespacedRef) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.NamespacedRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ObjectRef) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.ObjectRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PoolCapacity) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.PoolCapacity"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PoolSelector) OpenAPIModelName() string {
	return "com.miloapis.go.ipam.pkg.apis.ipam.v1alpha1.PoolSelector"
}
