#!/usr/bin/env bash
# Bundle k6 test scripts with their lib dependencies into self-contained files.
#
# The k6 operator references a single ConfigMap key per TestRun, so we cannot
# rely on relative imports across files. This script reads the shared lib at
# test/load/lib/ipam-client.js, strips its lib import from each test script,
# and prepends the lib content to produce self-contained files in
# config/components/k6-performance-tests/generated/.
#
# Run via: task -t test/load/Taskfile.yaml generate

set -euo pipefail

ROOT_DIR="${ROOT_DIR:-$(pwd)}"
SRC_DIR="${ROOT_DIR}/test/load/src"
LIB_FILE="${ROOT_DIR}/test/load/lib/ipam-client.js"
DEST_DIR="${ROOT_DIR}/config/components/k6-performance-tests/generated"

if [ ! -f "${LIB_FILE}" ]; then
  echo "ERROR: lib file not found at ${LIB_FILE}" >&2
  exit 1
fi

mkdir -p "${DEST_DIR}"

count=0
for script in "${SRC_DIR}"/*.js; do
  [ -f "${script}" ] || continue
  name=$(basename "${script}")
  out="${DEST_DIR}/${name}"

  {
    echo "// Code generated by hack/bundle-k6.sh. DO NOT EDIT."
    echo "// Source: test/load/src/${name}"
    echo "// Lib:    test/load/lib/ipam-client.js"
    echo ""
    cat "${LIB_FILE}"
    echo ""
    python3 - "${script}" <<'PY'
import re, sys
src = open(sys.argv[1]).read()
# Multi-line named import: import { a, b, c } from '../lib/ipam-client.js';
src = re.sub(
    r"^import\s*\{[^}]*\}\s*from\s*'\.\./lib/ipam-client\.js';\s*\n",
    '',
    src,
    flags=re.MULTILINE,
)
# Single-line default import: import foo from '../lib/ipam-client.js';
src = re.sub(
    r"^import\s+\w+\s+from\s+'\.\./lib/ipam-client\.js';\s*\n",
    '',
    src,
    flags=re.MULTILINE,
)
# Drop duplicate http import (the bundled lib already provides it).
src = re.sub(
    r"^import http from 'k6/http';\s*\n",
    '',
    src,
    flags=re.MULTILINE,
)
sys.stdout.write(src)
PY
  } > "${out}"

  echo "  ok  ${name}"
  count=$((count + 1))
done

echo ""
echo "Generated ${count} bundled k6 scripts in ${DEST_DIR}"
