apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: ipam-system
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ipam.miloapis.com
type: Opaque
stringData:
  dsn: "postgres://ipam:devpassword@postgres-postgresql.ipam-system.svc.cluster.local:5432/ipam?sslmode=disable"
  password: "devpassword"
