apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: nats-system
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: nats
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: nats-system
      interval: 1h
  values:
    config:
      cluster:
        enabled: false
      jetstream:
        enabled: true
        fileStore:
          enabled: true
          pvc:
            enabled: true
            size: 1Gi
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 256Mi
  install:
    crds: CreateReplace
    createNamespace: false
  upgrade:
    crds: CreateReplace
