// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ASNClaimLister helps list ASNClaims.
// All objects returned here must be treated as read-only.
type ASNClaimLister interface {
	// List lists all ASNClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.ASNClaim, err error)
	// ASNClaims returns an object that can list and get ASNClaims.
	ASNClaims(namespace string) ASNClaimNamespaceLister
	ASNClaimListerExpansion
}

// aSNClaimLister implements the ASNClaimLister interface.
type aSNClaimLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.ASNClaim]
}

// NewASNClaimLister returns a new ASNClaimLister.
func NewASNClaimLister(indexer cache.Indexer) ASNClaimLister {
	return &aSNClaimLister{listers.New[*ipamv1alpha1.ASNClaim](indexer, ipamv1alpha1.Resource("asnclaim"))}
}

// ASNClaims returns an object that can list and get ASNClaims.
func (s *aSNClaimLister) ASNClaims(namespace string) ASNClaimNamespaceLister {
	return aSNClaimNamespaceLister{listers.NewNamespaced[*ipamv1alpha1.ASNClaim](s.ResourceIndexer, namespace)}
}

// ASNClaimNamespaceLister helps list and get ASNClaims.
// All objects returned here must be treated as read-only.
type ASNClaimNamespaceLister interface {
	// List lists all ASNClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.ASNClaim, err error)
	// Get retrieves the ASNClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.ASNClaim, error)
	ASNClaimNamespaceListerExpansion
}

// aSNClaimNamespaceLister implements the ASNClaimNamespaceLister
// interface.
type aSNClaimNamespaceLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.ASNClaim]
}
