// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ASNPoolClassLister helps list ASNPoolClasses.
// All objects returned here must be treated as read-only.
type ASNPoolClassLister interface {
	// List lists all ASNPoolClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.ASNPoolClass, err error)
	// Get retrieves the ASNPoolClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.ASNPoolClass, error)
	ASNPoolClassListerExpansion
}

// aSNPoolClassLister implements the ASNPoolClassLister interface.
type aSNPoolClassLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.ASNPoolClass]
}

// NewASNPoolClassLister returns a new ASNPoolClassLister.
func NewASNPoolClassLister(indexer cache.Indexer) ASNPoolClassLister {
	return &aSNPoolClassLister{listers.New[*ipamv1alpha1.ASNPoolClass](indexer, ipamv1alpha1.Resource("asnpoolclass"))}
}
