// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ASNPoolLister helps list ASNPools.
// All objects returned here must be treated as read-only.
type ASNPoolLister interface {
	// List lists all ASNPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.ASNPool, err error)
	// Get retrieves the ASNPool from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.ASNPool, error)
	ASNPoolListerExpansion
}

// aSNPoolLister implements the ASNPoolLister interface.
type aSNPoolLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.ASNPool]
}

// NewASNPoolLister returns a new ASNPoolLister.
func NewASNPoolLister(indexer cache.Indexer) ASNPoolLister {
	return &aSNPoolLister{listers.New[*ipamv1alpha1.ASNPool](indexer, ipamv1alpha1.Resource("asnpool"))}
}
