// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IPAllocationListerExpansion allows custom methods to be added to
// IPAllocationLister.
type IPAllocationListerExpansion interface{}

// IPAllocationNamespaceListerExpansion allows custom methods to be added to
// IPAllocationNamespaceLister.
type IPAllocationNamespaceListerExpansion interface{}

// IPClaimListerExpansion allows custom methods to be added to
// IPClaimLister.
type IPClaimListerExpansion interface{}

// IPClaimNamespaceListerExpansion allows custom methods to be added to
// IPClaimNamespaceLister.
type IPClaimNamespaceListerExpansion interface{}

// IPPoolListerExpansion allows custom methods to be added to
// IPPoolLister.
type IPPoolListerExpansion interface{}
