// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ASNClaimListerExpansion allows custom methods to be added to
// ASNClaimLister.
type ASNClaimListerExpansion interface{}

// ASNClaimNamespaceListerExpansion allows custom methods to be added to
// ASNClaimNamespaceLister.
type ASNClaimNamespaceListerExpansion interface{}

// ASNPoolListerExpansion allows custom methods to be added to
// ASNPoolLister.
type ASNPoolListerExpansion interface{}

// ASNPoolClassListerExpansion allows custom methods to be added to
// ASNPoolClassLister.
type ASNPoolClassListerExpansion interface{}

// IPAddressListerExpansion allows custom methods to be added to
// IPAddressLister.
type IPAddressListerExpansion interface{}

// IPAddressNamespaceListerExpansion allows custom methods to be added to
// IPAddressNamespaceLister.
type IPAddressNamespaceListerExpansion interface{}

// IPAddressClaimListerExpansion allows custom methods to be added to
// IPAddressClaimLister.
type IPAddressClaimListerExpansion interface{}

// IPAddressClaimNamespaceListerExpansion allows custom methods to be added to
// IPAddressClaimNamespaceLister.
type IPAddressClaimNamespaceListerExpansion interface{}

// IPPrefixListerExpansion allows custom methods to be added to
// IPPrefixLister.
type IPPrefixListerExpansion interface{}

// IPPrefixClaimListerExpansion allows custom methods to be added to
// IPPrefixClaimLister.
type IPPrefixClaimListerExpansion interface{}

// IPPrefixClaimNamespaceListerExpansion allows custom methods to be added to
// IPPrefixClaimNamespaceLister.
type IPPrefixClaimNamespaceListerExpansion interface{}

// IPPrefixClassListerExpansion allows custom methods to be added to
// IPPrefixClassLister.
type IPPrefixClassListerExpansion interface{}
