// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// IPPrefixListerExpansion allows custom methods to be added to
// IPPrefixLister.
type IPPrefixListerExpansion any

// IPPrefixClaimListerExpansion allows custom methods to be added to
// IPPrefixClaimLister.
type IPPrefixClaimListerExpansion any

// IPPrefixClaimNamespaceListerExpansion allows custom methods to be added to
// IPPrefixClaimNamespaceLister.
type IPPrefixClaimNamespaceListerExpansion any

// IPPrefixClassListerExpansion allows custom methods to be added to
// IPPrefixClassLister.
type IPPrefixClassListerExpansion any
