// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPAddressLister helps list IPAddresses.
// All objects returned here must be treated as read-only.
type IPAddressLister interface {
	// List lists all IPAddresses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPAddress, err error)
	// IPAddresses returns an object that can list and get IPAddresses.
	IPAddresses(namespace string) IPAddressNamespaceLister
	IPAddressListerExpansion
}

// iPAddressLister implements the IPAddressLister interface.
type iPAddressLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPAddress]
}

// NewIPAddressLister returns a new IPAddressLister.
func NewIPAddressLister(indexer cache.Indexer) IPAddressLister {
	return &iPAddressLister{listers.New[*ipamv1alpha1.IPAddress](indexer, ipamv1alpha1.Resource("ipaddress"))}
}

// IPAddresses returns an object that can list and get IPAddresses.
func (s *iPAddressLister) IPAddresses(namespace string) IPAddressNamespaceLister {
	return iPAddressNamespaceLister{listers.NewNamespaced[*ipamv1alpha1.IPAddress](s.ResourceIndexer, namespace)}
}

// IPAddressNamespaceLister helps list and get IPAddresses.
// All objects returned here must be treated as read-only.
type IPAddressNamespaceLister interface {
	// List lists all IPAddresses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPAddress, err error)
	// Get retrieves the IPAddress from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPAddress, error)
	IPAddressNamespaceListerExpansion
}

// iPAddressNamespaceLister implements the IPAddressNamespaceLister
// interface.
type iPAddressNamespaceLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPAddress]
}
