// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPAddressClaimLister helps list IPAddressClaims.
// All objects returned here must be treated as read-only.
type IPAddressClaimLister interface {
	// List lists all IPAddressClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPAddressClaim, err error)
	// IPAddressClaims returns an object that can list and get IPAddressClaims.
	IPAddressClaims(namespace string) IPAddressClaimNamespaceLister
	IPAddressClaimListerExpansion
}

// iPAddressClaimLister implements the IPAddressClaimLister interface.
type iPAddressClaimLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPAddressClaim]
}

// NewIPAddressClaimLister returns a new IPAddressClaimLister.
func NewIPAddressClaimLister(indexer cache.Indexer) IPAddressClaimLister {
	return &iPAddressClaimLister{listers.New[*ipamv1alpha1.IPAddressClaim](indexer, ipamv1alpha1.Resource("ipaddressclaim"))}
}

// IPAddressClaims returns an object that can list and get IPAddressClaims.
func (s *iPAddressClaimLister) IPAddressClaims(namespace string) IPAddressClaimNamespaceLister {
	return iPAddressClaimNamespaceLister{listers.NewNamespaced[*ipamv1alpha1.IPAddressClaim](s.ResourceIndexer, namespace)}
}

// IPAddressClaimNamespaceLister helps list and get IPAddressClaims.
// All objects returned here must be treated as read-only.
type IPAddressClaimNamespaceLister interface {
	// List lists all IPAddressClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPAddressClaim, err error)
	// Get retrieves the IPAddressClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPAddressClaim, error)
	IPAddressClaimNamespaceListerExpansion
}

// iPAddressClaimNamespaceLister implements the IPAddressClaimNamespaceLister
// interface.
type iPAddressClaimNamespaceLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPAddressClaim]
}
