// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPClaimLister helps list IPClaims.
// All objects returned here must be treated as read-only.
type IPClaimLister interface {
	// List lists all IPClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPClaim, err error)
	// IPClaims returns an object that can list and get IPClaims.
	IPClaims(namespace string) IPClaimNamespaceLister
	IPClaimListerExpansion
}

// iPClaimLister implements the IPClaimLister interface.
type iPClaimLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPClaim]
}

// NewIPClaimLister returns a new IPClaimLister.
func NewIPClaimLister(indexer cache.Indexer) IPClaimLister {
	return &iPClaimLister{listers.New[*ipamv1alpha1.IPClaim](indexer, ipamv1alpha1.Resource("ipclaim"))}
}

// IPClaims returns an object that can list and get IPClaims.
func (s *iPClaimLister) IPClaims(namespace string) IPClaimNamespaceLister {
	return iPClaimNamespaceLister{listers.NewNamespaced[*ipamv1alpha1.IPClaim](s.ResourceIndexer, namespace)}
}

// IPClaimNamespaceLister helps list and get IPClaims.
// All objects returned here must be treated as read-only.
type IPClaimNamespaceLister interface {
	// List lists all IPClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPClaim, err error)
	// Get retrieves the IPClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPClaim, error)
	IPClaimNamespaceListerExpansion
}

// iPClaimNamespaceLister implements the IPClaimNamespaceLister
// interface.
type iPClaimNamespaceLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPClaim]
}
