// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPClassLister helps list IPClasses.
// All objects returned here must be treated as read-only.
type IPClassLister interface {
	// List lists all IPClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPClass, err error)
	// Get retrieves the IPClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPClass, error)
	IPClassListerExpansion
}

// iPClassLister implements the IPClassLister interface.
type iPClassLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPClass]
}

// NewIPClassLister returns a new IPClassLister.
func NewIPClassLister(indexer cache.Indexer) IPClassLister {
	return &iPClassLister{listers.New[*ipamv1alpha1.IPClass](indexer, ipamv1alpha1.Resource("ipclass"))}
}
