// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPPrefixClassLister helps list IPPrefixClasses.
// All objects returned here must be treated as read-only.
type IPPrefixClassLister interface {
	// List lists all IPPrefixClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPPrefixClass, err error)
	// Get retrieves the IPPrefixClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPPrefixClass, error)
	IPPrefixClassListerExpansion
}

// iPPrefixClassLister implements the IPPrefixClassLister interface.
type iPPrefixClassLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPPrefixClass]
}

// NewIPPrefixClassLister returns a new IPPrefixClassLister.
func NewIPPrefixClassLister(indexer cache.Indexer) IPPrefixClassLister {
	return &iPPrefixClassLister{listers.New[*ipamv1alpha1.IPPrefixClass](indexer, ipamv1alpha1.Resource("ipprefixclass"))}
}
