// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPPrefixClaimLister helps list IPPrefixClaims.
// All objects returned here must be treated as read-only.
type IPPrefixClaimLister interface {
	// List lists all IPPrefixClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPPrefixClaim, err error)
	// IPPrefixClaims returns an object that can list and get IPPrefixClaims.
	IPPrefixClaims(namespace string) IPPrefixClaimNamespaceLister
	IPPrefixClaimListerExpansion
}

// iPPrefixClaimLister implements the IPPrefixClaimLister interface.
type iPPrefixClaimLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPPrefixClaim]
}

// NewIPPrefixClaimLister returns a new IPPrefixClaimLister.
func NewIPPrefixClaimLister(indexer cache.Indexer) IPPrefixClaimLister {
	return &iPPrefixClaimLister{listers.New[*ipamv1alpha1.IPPrefixClaim](indexer, ipamv1alpha1.Resource("ipprefixclaim"))}
}

// IPPrefixClaims returns an object that can list and get IPPrefixClaims.
func (s *iPPrefixClaimLister) IPPrefixClaims(namespace string) IPPrefixClaimNamespaceLister {
	return iPPrefixClaimNamespaceLister{listers.NewNamespaced[*ipamv1alpha1.IPPrefixClaim](s.ResourceIndexer, namespace)}
}

// IPPrefixClaimNamespaceLister helps list and get IPPrefixClaims.
// All objects returned here must be treated as read-only.
type IPPrefixClaimNamespaceLister interface {
	// List lists all IPPrefixClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPPrefixClaim, err error)
	// Get retrieves the IPPrefixClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPPrefixClaim, error)
	IPPrefixClaimNamespaceListerExpansion
}

// iPPrefixClaimNamespaceLister implements the IPPrefixClaimNamespaceLister
// interface.
type iPPrefixClaimNamespaceLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPPrefixClaim]
}
