// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IPPrefixLister helps list IPPrefixes.
// All objects returned here must be treated as read-only.
type IPPrefixLister interface {
	// List lists all IPPrefixes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ipamv1alpha1.IPPrefix, err error)
	// Get retrieves the IPPrefix from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ipamv1alpha1.IPPrefix, error)
	IPPrefixListerExpansion
}

// iPPrefixLister implements the IPPrefixLister interface.
type iPPrefixLister struct {
	listers.ResourceIndexer[*ipamv1alpha1.IPPrefix]
}

// NewIPPrefixLister returns a new IPPrefixLister.
func NewIPPrefixLister(indexer cache.Indexer) IPPrefixLister {
	return &iPPrefixLister{listers.New[*ipamv1alpha1.IPPrefix](indexer, ipamv1alpha1.Resource("ipprefix"))}
}
