// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	versioned "go.miloapis.com/ipam/pkg/client/clientset/versioned"
	internalinterfaces "go.miloapis.com/ipam/pkg/client/informers/externalversions/internalinterfaces"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/listers/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ASNPoolInformer provides access to a shared informer and lister for
// ASNPools.
type ASNPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ipamv1alpha1.ASNPoolLister
}

type aSNPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewASNPoolInformer constructs a new informer for ASNPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewASNPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredASNPoolInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredASNPoolInformer constructs a new informer for ASNPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredASNPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPools().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPools().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPools().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPools().Watch(ctx, options)
			},
		}, client),
		&apisipamv1alpha1.ASNPool{},
		resyncPeriod,
		indexers,
	)
}

func (f *aSNPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredASNPoolInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aSNPoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisipamv1alpha1.ASNPool{}, f.defaultInformer)
}

func (f *aSNPoolInformer) Lister() ipamv1alpha1.ASNPoolLister {
	return ipamv1alpha1.NewASNPoolLister(f.Informer().GetIndexer())
}
