// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	versioned "go.miloapis.com/ipam/pkg/client/clientset/versioned"
	internalinterfaces "go.miloapis.com/ipam/pkg/client/informers/externalversions/internalinterfaces"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/listers/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ASNPoolClassInformer provides access to a shared informer and lister for
// ASNPoolClasses.
type ASNPoolClassInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ipamv1alpha1.ASNPoolClassLister
}

type aSNPoolClassInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewASNPoolClassInformer constructs a new informer for ASNPoolClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewASNPoolClassInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredASNPoolClassInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredASNPoolClassInformer constructs a new informer for ASNPoolClass type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredASNPoolClassInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPoolClasses().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPoolClasses().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPoolClasses().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().ASNPoolClasses().Watch(ctx, options)
			},
		}, client),
		&apisipamv1alpha1.ASNPoolClass{},
		resyncPeriod,
		indexers,
	)
}

func (f *aSNPoolClassInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredASNPoolClassInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aSNPoolClassInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisipamv1alpha1.ASNPoolClass{}, f.defaultInformer)
}

func (f *aSNPoolClassInformer) Lister() ipamv1alpha1.ASNPoolClassLister {
	return ipamv1alpha1.NewASNPoolClassLister(f.Informer().GetIndexer())
}
