// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "go.miloapis.com/ipam/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// IPAddresses returns a IPAddressInformer.
	IPAddresses() IPAddressInformer
	// IPAddressClaims returns a IPAddressClaimInformer.
	IPAddressClaims() IPAddressClaimInformer
	// IPPrefixes returns a IPPrefixInformer.
	IPPrefixes() IPPrefixInformer
	// IPPrefixClaims returns a IPPrefixClaimInformer.
	IPPrefixClaims() IPPrefixClaimInformer
	// IPPrefixClasses returns a IPPrefixClassInformer.
	IPPrefixClasses() IPPrefixClassInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// IPAddresses returns a IPAddressInformer.
func (v *version) IPAddresses() IPAddressInformer {
	return &iPAddressInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPAddressClaims returns a IPAddressClaimInformer.
func (v *version) IPAddressClaims() IPAddressClaimInformer {
	return &iPAddressClaimInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPPrefixes returns a IPPrefixInformer.
func (v *version) IPPrefixes() IPPrefixInformer {
	return &iPPrefixInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// IPPrefixClaims returns a IPPrefixClaimInformer.
func (v *version) IPPrefixClaims() IPPrefixClaimInformer {
	return &iPPrefixClaimInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IPPrefixClasses returns a IPPrefixClassInformer.
func (v *version) IPPrefixClasses() IPPrefixClassInformer {
	return &iPPrefixClassInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
