// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	versioned "go.miloapis.com/ipam/pkg/client/clientset/versioned"
	internalinterfaces "go.miloapis.com/ipam/pkg/client/informers/externalversions/internalinterfaces"
	ipamv1alpha1 "go.miloapis.com/ipam/pkg/client/listers/ipam/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IPPrefixInformer provides access to a shared informer and lister for
// IPPrefixes.
type IPPrefixInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ipamv1alpha1.IPPrefixLister
}

type iPPrefixInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewIPPrefixInformer constructs a new informer for IPPrefix type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIPPrefixInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIPPrefixInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredIPPrefixInformer constructs a new informer for IPPrefix type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIPPrefixInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().IPPrefixes().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().IPPrefixes().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().IPPrefixes().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IpamV1alpha1().IPPrefixes().Watch(ctx, options)
			},
		}, client),
		&apisipamv1alpha1.IPPrefix{},
		resyncPeriod,
		indexers,
	)
}

func (f *iPPrefixInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIPPrefixInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iPPrefixInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisipamv1alpha1.IPPrefix{}, f.defaultInformer)
}

func (f *iPPrefixInformer) Lister() ipamv1alpha1.IPPrefixLister {
	return ipamv1alpha1.NewIPPrefixLister(f.Informer().GetIndexer())
}
