// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ASNClaimsGetter has a method to return a ASNClaimInterface.
// A group's client should implement this interface.
type ASNClaimsGetter interface {
	ASNClaims(namespace string) ASNClaimInterface
}

// ASNClaimInterface has methods to work with ASNClaim resources.
type ASNClaimInterface interface {
	Create(ctx context.Context, aSNClaim *ipamv1alpha1.ASNClaim, opts v1.CreateOptions) (*ipamv1alpha1.ASNClaim, error)
	Update(ctx context.Context, aSNClaim *ipamv1alpha1.ASNClaim, opts v1.UpdateOptions) (*ipamv1alpha1.ASNClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aSNClaim *ipamv1alpha1.ASNClaim, opts v1.UpdateOptions) (*ipamv1alpha1.ASNClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.ASNClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.ASNClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.ASNClaim, err error)
	ASNClaimExpansion
}

// aSNClaims implements ASNClaimInterface
type aSNClaims struct {
	*gentype.ClientWithList[*ipamv1alpha1.ASNClaim, *ipamv1alpha1.ASNClaimList]
}

// newASNClaims returns a ASNClaims
func newASNClaims(c *IpamV1alpha1Client, namespace string) *aSNClaims {
	return &aSNClaims{
		gentype.NewClientWithList[*ipamv1alpha1.ASNClaim, *ipamv1alpha1.ASNClaimList](
			"asnclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ipamv1alpha1.ASNClaim { return &ipamv1alpha1.ASNClaim{} },
			func() *ipamv1alpha1.ASNClaimList { return &ipamv1alpha1.ASNClaimList{} },
		),
	}
}
