// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ASNPoolClassesGetter has a method to return a ASNPoolClassInterface.
// A group's client should implement this interface.
type ASNPoolClassesGetter interface {
	ASNPoolClasses() ASNPoolClassInterface
}

// ASNPoolClassInterface has methods to work with ASNPoolClass resources.
type ASNPoolClassInterface interface {
	Create(ctx context.Context, aSNPoolClass *ipamv1alpha1.ASNPoolClass, opts v1.CreateOptions) (*ipamv1alpha1.ASNPoolClass, error)
	Update(ctx context.Context, aSNPoolClass *ipamv1alpha1.ASNPoolClass, opts v1.UpdateOptions) (*ipamv1alpha1.ASNPoolClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.ASNPoolClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.ASNPoolClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.ASNPoolClass, err error)
	ASNPoolClassExpansion
}

// aSNPoolClasses implements ASNPoolClassInterface
type aSNPoolClasses struct {
	*gentype.ClientWithList[*ipamv1alpha1.ASNPoolClass, *ipamv1alpha1.ASNPoolClassList]
}

// newASNPoolClasses returns a ASNPoolClasses
func newASNPoolClasses(c *IpamV1alpha1Client) *aSNPoolClasses {
	return &aSNPoolClasses{
		gentype.NewClientWithList[*ipamv1alpha1.ASNPoolClass, *ipamv1alpha1.ASNPoolClassList](
			"asnpoolclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ipamv1alpha1.ASNPoolClass { return &ipamv1alpha1.ASNPoolClass{} },
			func() *ipamv1alpha1.ASNPoolClassList { return &ipamv1alpha1.ASNPoolClassList{} },
		),
	}
}
