// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ASNPoolsGetter has a method to return a ASNPoolInterface.
// A group's client should implement this interface.
type ASNPoolsGetter interface {
	ASNPools() ASNPoolInterface
}

// ASNPoolInterface has methods to work with ASNPool resources.
type ASNPoolInterface interface {
	Create(ctx context.Context, aSNPool *ipamv1alpha1.ASNPool, opts v1.CreateOptions) (*ipamv1alpha1.ASNPool, error)
	Update(ctx context.Context, aSNPool *ipamv1alpha1.ASNPool, opts v1.UpdateOptions) (*ipamv1alpha1.ASNPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aSNPool *ipamv1alpha1.ASNPool, opts v1.UpdateOptions) (*ipamv1alpha1.ASNPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.ASNPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.ASNPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.ASNPool, err error)
	ASNPoolExpansion
}

// aSNPools implements ASNPoolInterface
type aSNPools struct {
	*gentype.ClientWithList[*ipamv1alpha1.ASNPool, *ipamv1alpha1.ASNPoolList]
}

// newASNPools returns a ASNPools
func newASNPools(c *IpamV1alpha1Client) *aSNPools {
	return &aSNPools{
		gentype.NewClientWithList[*ipamv1alpha1.ASNPool, *ipamv1alpha1.ASNPoolList](
			"asnpools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ipamv1alpha1.ASNPool { return &ipamv1alpha1.ASNPool{} },
			func() *ipamv1alpha1.ASNPoolList { return &ipamv1alpha1.ASNPoolList{} },
		),
	}
}
