// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ASNClaimExpansion interface{}

type ASNPoolExpansion interface{}

type ASNPoolClassExpansion interface{}

type IPAddressExpansion interface{}

type IPAddressClaimExpansion interface{}

type IPPrefixExpansion interface{}

type IPPrefixClaimExpansion interface{}

type IPPrefixClassExpansion interface{}
