// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPAddressClaimsGetter has a method to return a IPAddressClaimInterface.
// A group's client should implement this interface.
type IPAddressClaimsGetter interface {
	IPAddressClaims(namespace string) IPAddressClaimInterface
}

// IPAddressClaimInterface has methods to work with IPAddressClaim resources.
type IPAddressClaimInterface interface {
	Create(ctx context.Context, iPAddressClaim *ipamv1alpha1.IPAddressClaim, opts v1.CreateOptions) (*ipamv1alpha1.IPAddressClaim, error)
	Update(ctx context.Context, iPAddressClaim *ipamv1alpha1.IPAddressClaim, opts v1.UpdateOptions) (*ipamv1alpha1.IPAddressClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPAddressClaim *ipamv1alpha1.IPAddressClaim, opts v1.UpdateOptions) (*ipamv1alpha1.IPAddressClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPAddressClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPAddressClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPAddressClaim, err error)
	IPAddressClaimExpansion
}

// iPAddressClaims implements IPAddressClaimInterface
type iPAddressClaims struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPAddressClaim, *ipamv1alpha1.IPAddressClaimList]
}

// newIPAddressClaims returns a IPAddressClaims
func newIPAddressClaims(c *IpamV1alpha1Client, namespace string) *iPAddressClaims {
	return &iPAddressClaims{
		gentype.NewClientWithList[*ipamv1alpha1.IPAddressClaim, *ipamv1alpha1.IPAddressClaimList](
			"ipaddressclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ipamv1alpha1.IPAddressClaim { return &ipamv1alpha1.IPAddressClaim{} },
			func() *ipamv1alpha1.IPAddressClaimList { return &ipamv1alpha1.IPAddressClaimList{} },
		),
	}
}
