// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPAddressesGetter has a method to return a IPAddressInterface.
// A group's client should implement this interface.
type IPAddressesGetter interface {
	IPAddresses(namespace string) IPAddressInterface
}

// IPAddressInterface has methods to work with IPAddress resources.
type IPAddressInterface interface {
	Create(ctx context.Context, iPAddress *ipamv1alpha1.IPAddress, opts v1.CreateOptions) (*ipamv1alpha1.IPAddress, error)
	Update(ctx context.Context, iPAddress *ipamv1alpha1.IPAddress, opts v1.UpdateOptions) (*ipamv1alpha1.IPAddress, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPAddress *ipamv1alpha1.IPAddress, opts v1.UpdateOptions) (*ipamv1alpha1.IPAddress, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPAddress, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPAddressList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPAddress, err error)
	IPAddressExpansion
}

// iPAddresses implements IPAddressInterface
type iPAddresses struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPAddress, *ipamv1alpha1.IPAddressList]
}

// newIPAddresses returns a IPAddresses
func newIPAddresses(c *IpamV1alpha1Client, namespace string) *iPAddresses {
	return &iPAddresses{
		gentype.NewClientWithList[*ipamv1alpha1.IPAddress, *ipamv1alpha1.IPAddressList](
			"ipaddresses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ipamv1alpha1.IPAddress { return &ipamv1alpha1.IPAddress{} },
			func() *ipamv1alpha1.IPAddressList { return &ipamv1alpha1.IPAddressList{} },
		),
	}
}
