// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPAllocationsGetter has a method to return a IPAllocationInterface.
// A group's client should implement this interface.
type IPAllocationsGetter interface {
	IPAllocations(namespace string) IPAllocationInterface
}

// IPAllocationInterface has methods to work with IPAllocation resources.
type IPAllocationInterface interface {
	Create(ctx context.Context, iPAllocation *ipamv1alpha1.IPAllocation, opts v1.CreateOptions) (*ipamv1alpha1.IPAllocation, error)
	Update(ctx context.Context, iPAllocation *ipamv1alpha1.IPAllocation, opts v1.UpdateOptions) (*ipamv1alpha1.IPAllocation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPAllocation *ipamv1alpha1.IPAllocation, opts v1.UpdateOptions) (*ipamv1alpha1.IPAllocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPAllocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPAllocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPAllocation, err error)
	IPAllocationExpansion
}

// iPAllocations implements IPAllocationInterface
type iPAllocations struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPAllocation, *ipamv1alpha1.IPAllocationList]
}

// newIPAllocations returns a IPAllocations
func newIPAllocations(c *IpamV1alpha1Client, namespace string) *iPAllocations {
	return &iPAllocations{
		gentype.NewClientWithList[*ipamv1alpha1.IPAllocation, *ipamv1alpha1.IPAllocationList](
			"ipallocations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ipamv1alpha1.IPAllocation { return &ipamv1alpha1.IPAllocation{} },
			func() *ipamv1alpha1.IPAllocationList { return &ipamv1alpha1.IPAllocationList{} },
		),
	}
}
