// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type IpamV1alpha1Interface interface {
	RESTClient() rest.Interface
	IPAllocationsGetter
	IPClaimsGetter
	IPPoolsGetter
}

// IpamV1alpha1Client is used to interact with features provided by the ipam.miloapis.com group.
type IpamV1alpha1Client struct {
	restClient rest.Interface
}

func (c *IpamV1alpha1Client) IPAllocations(namespace string) IPAllocationInterface {
	return newIPAllocations(c, namespace)
}

func (c *IpamV1alpha1Client) IPClaims(namespace string) IPClaimInterface {
	return newIPClaims(c, namespace)
}

func (c *IpamV1alpha1Client) IPPools() IPPoolInterface {
	return newIPPools(c)
}

// NewForConfig creates a new IpamV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*IpamV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new IpamV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*IpamV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &IpamV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new IpamV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *IpamV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new IpamV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *IpamV1alpha1Client {
	return &IpamV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := ipamv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *IpamV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
