// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPClassesGetter has a method to return a IPClassInterface.
// A group's client should implement this interface.
type IPClassesGetter interface {
	IPClasses() IPClassInterface
}

// IPClassInterface has methods to work with IPClass resources.
type IPClassInterface interface {
	Create(ctx context.Context, iPClass *ipamv1alpha1.IPClass, opts v1.CreateOptions) (*ipamv1alpha1.IPClass, error)
	Update(ctx context.Context, iPClass *ipamv1alpha1.IPClass, opts v1.UpdateOptions) (*ipamv1alpha1.IPClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPClass *ipamv1alpha1.IPClass, opts v1.UpdateOptions) (*ipamv1alpha1.IPClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPClass, err error)
	IPClassExpansion
}

// iPClasses implements IPClassInterface
type iPClasses struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPClass, *ipamv1alpha1.IPClassList]
}

// newIPClasses returns a IPClasses
func newIPClasses(c *IpamV1alpha1Client) *iPClasses {
	return &iPClasses{
		gentype.NewClientWithList[*ipamv1alpha1.IPClass, *ipamv1alpha1.IPClassList](
			"ipclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ipamv1alpha1.IPClass { return &ipamv1alpha1.IPClass{} },
			func() *ipamv1alpha1.IPClassList { return &ipamv1alpha1.IPClassList{} },
		),
	}
}
