// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPClaimsGetter has a method to return a IPClaimInterface.
// A group's client should implement this interface.
type IPClaimsGetter interface {
	IPClaims(namespace string) IPClaimInterface
}

// IPClaimInterface has methods to work with IPClaim resources.
type IPClaimInterface interface {
	Create(ctx context.Context, iPClaim *ipamv1alpha1.IPClaim, opts v1.CreateOptions) (*ipamv1alpha1.IPClaim, error)
	Update(ctx context.Context, iPClaim *ipamv1alpha1.IPClaim, opts v1.UpdateOptions) (*ipamv1alpha1.IPClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPClaim *ipamv1alpha1.IPClaim, opts v1.UpdateOptions) (*ipamv1alpha1.IPClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPClaim, err error)
	IPClaimExpansion
}

// iPClaims implements IPClaimInterface
type iPClaims struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPClaim, *ipamv1alpha1.IPClaimList]
}

// newIPClaims returns a IPClaims
func newIPClaims(c *IpamV1alpha1Client, namespace string) *iPClaims {
	return &iPClaims{
		gentype.NewClientWithList[*ipamv1alpha1.IPClaim, *ipamv1alpha1.IPClaimList](
			"ipclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ipamv1alpha1.IPClaim { return &ipamv1alpha1.IPClaim{} },
			func() *ipamv1alpha1.IPClaimList { return &ipamv1alpha1.IPClaimList{} },
		),
	}
}
