// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPPoolsGetter has a method to return a IPPoolInterface.
// A group's client should implement this interface.
type IPPoolsGetter interface {
	IPPools() IPPoolInterface
}

// IPPoolInterface has methods to work with IPPool resources.
type IPPoolInterface interface {
	Create(ctx context.Context, iPPool *ipamv1alpha1.IPPool, opts v1.CreateOptions) (*ipamv1alpha1.IPPool, error)
	Update(ctx context.Context, iPPool *ipamv1alpha1.IPPool, opts v1.UpdateOptions) (*ipamv1alpha1.IPPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPPool *ipamv1alpha1.IPPool, opts v1.UpdateOptions) (*ipamv1alpha1.IPPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPPool, err error)
	IPPoolExpansion
}

// iPPools implements IPPoolInterface
type iPPools struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPPool, *ipamv1alpha1.IPPoolList]
}

// newIPPools returns a IPPools
func newIPPools(c *IpamV1alpha1Client) *iPPools {
	return &iPPools{
		gentype.NewClientWithList[*ipamv1alpha1.IPPool, *ipamv1alpha1.IPPoolList](
			"ippools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ipamv1alpha1.IPPool { return &ipamv1alpha1.IPPool{} },
			func() *ipamv1alpha1.IPPoolList { return &ipamv1alpha1.IPPoolList{} },
		),
	}
}
