// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPPrefixesGetter has a method to return a IPPrefixInterface.
// A group's client should implement this interface.
type IPPrefixesGetter interface {
	IPPrefixes() IPPrefixInterface
}

// IPPrefixInterface has methods to work with IPPrefix resources.
type IPPrefixInterface interface {
	Create(ctx context.Context, iPPrefix *ipamv1alpha1.IPPrefix, opts v1.CreateOptions) (*ipamv1alpha1.IPPrefix, error)
	Update(ctx context.Context, iPPrefix *ipamv1alpha1.IPPrefix, opts v1.UpdateOptions) (*ipamv1alpha1.IPPrefix, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPPrefix *ipamv1alpha1.IPPrefix, opts v1.UpdateOptions) (*ipamv1alpha1.IPPrefix, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPPrefix, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPPrefixList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPPrefix, err error)
	IPPrefixExpansion
}

// iPPrefixes implements IPPrefixInterface
type iPPrefixes struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPPrefix, *ipamv1alpha1.IPPrefixList]
}

// newIPPrefixes returns a IPPrefixes
func newIPPrefixes(c *IpamV1alpha1Client) *iPPrefixes {
	return &iPPrefixes{
		gentype.NewClientWithList(
			"ipprefixes",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ipamv1alpha1.IPPrefix { return &ipamv1alpha1.IPPrefix{} },
			func() *ipamv1alpha1.IPPrefixList { return &ipamv1alpha1.IPPrefixList{} },
		),
	}
}
