// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPPrefixClassesGetter has a method to return a IPPrefixClassInterface.
// A group's client should implement this interface.
type IPPrefixClassesGetter interface {
	IPPrefixClasses() IPPrefixClassInterface
}

// IPPrefixClassInterface has methods to work with IPPrefixClass resources.
type IPPrefixClassInterface interface {
	Create(ctx context.Context, iPPrefixClass *ipamv1alpha1.IPPrefixClass, opts v1.CreateOptions) (*ipamv1alpha1.IPPrefixClass, error)
	Update(ctx context.Context, iPPrefixClass *ipamv1alpha1.IPPrefixClass, opts v1.UpdateOptions) (*ipamv1alpha1.IPPrefixClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPPrefixClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPPrefixClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPPrefixClass, err error)
	IPPrefixClassExpansion
}

// iPPrefixClasses implements IPPrefixClassInterface
type iPPrefixClasses struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPPrefixClass, *ipamv1alpha1.IPPrefixClassList]
}

// newIPPrefixClasses returns a IPPrefixClasses
func newIPPrefixClasses(c *IpamV1alpha1Client) *iPPrefixClasses {
	return &iPPrefixClasses{
		gentype.NewClientWithList[*ipamv1alpha1.IPPrefixClass, *ipamv1alpha1.IPPrefixClassList](
			"ipprefixclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ipamv1alpha1.IPPrefixClass { return &ipamv1alpha1.IPPrefixClass{} },
			func() *ipamv1alpha1.IPPrefixClassList { return &ipamv1alpha1.IPPrefixClassList{} },
		),
	}
}
