// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ipamv1alpha1 "go.miloapis.com/ipam/pkg/apis/ipam/v1alpha1"
	scheme "go.miloapis.com/ipam/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPPrefixClaimsGetter has a method to return a IPPrefixClaimInterface.
// A group's client should implement this interface.
type IPPrefixClaimsGetter interface {
	IPPrefixClaims(namespace string) IPPrefixClaimInterface
}

// IPPrefixClaimInterface has methods to work with IPPrefixClaim resources.
type IPPrefixClaimInterface interface {
	Create(ctx context.Context, iPPrefixClaim *ipamv1alpha1.IPPrefixClaim, opts v1.CreateOptions) (*ipamv1alpha1.IPPrefixClaim, error)
	Update(ctx context.Context, iPPrefixClaim *ipamv1alpha1.IPPrefixClaim, opts v1.UpdateOptions) (*ipamv1alpha1.IPPrefixClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPPrefixClaim *ipamv1alpha1.IPPrefixClaim, opts v1.UpdateOptions) (*ipamv1alpha1.IPPrefixClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ipamv1alpha1.IPPrefixClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*ipamv1alpha1.IPPrefixClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ipamv1alpha1.IPPrefixClaim, err error)
	IPPrefixClaimExpansion
}

// iPPrefixClaims implements IPPrefixClaimInterface
type iPPrefixClaims struct {
	*gentype.ClientWithList[*ipamv1alpha1.IPPrefixClaim, *ipamv1alpha1.IPPrefixClaimList]
}

// newIPPrefixClaims returns a IPPrefixClaims
func newIPPrefixClaims(c *IpamV1alpha1Client, namespace string) *iPPrefixClaims {
	return &iPPrefixClaims{
		gentype.NewClientWithList(
			"ipprefixclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ipamv1alpha1.IPPrefixClaim { return &ipamv1alpha1.IPPrefixClaim{} },
			func() *ipamv1alpha1.IPPrefixClaimList { return &ipamv1alpha1.IPPrefixClaimList{} },
		),
	}
}
