apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Basic example: provision an IPPrefixClass + IPPrefix, then make a prefix
# claim.
#
# Apply with:
#   kubectl apply -k examples/basic/

resources:
  - ipprefix.yaml
  - ipprefixclaim.yaml
